# Autogenerated wrapper script for YAC_jll for aarch64-linux-musl-mpi+mpiabi
export libyac_core, libyac_mci, libyac_mtime, libyac_pak, libyac_utils

using yaxt_jll
using libfyaml_jll
using NetCDF_jll
using OpenBLAS32_jll
using CompilerSupportLibraries_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("YAC")
JLLWrappers.@declare_library_product(libyac_core, "libyac_core.so")
JLLWrappers.@declare_library_product(libyac_mci, "libyac_mci.so")
JLLWrappers.@declare_library_product(libyac_mtime, "libyac_mtime.so")
JLLWrappers.@declare_library_product(libyac_pak, "libyac_pak.so")
JLLWrappers.@declare_library_product(libyac_utils, "libyac_utils.so")
function __init__()
    JLLWrappers.@generate_init_header(yaxt_jll, libfyaml_jll, NetCDF_jll, OpenBLAS32_jll, CompilerSupportLibraries_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libyac_core,
        "lib/libyac_core.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_mci,
        "lib/libyac_mci.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_mtime,
        "lib/libyac_mtime.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_pak,
        "lib/libyac_pak.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_utils,
        "lib/libyac_utils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
