# Autogenerated wrapper script for YAC_jll for x86_64-apple-darwin-mpi+openmpi
export libyac_core, libyac_mci, libyac_mtime, libyac_pak, libyac_utils

using yaxt_jll
using libfyaml_jll
using NetCDF_jll
using OpenBLAS32_jll
using CompilerSupportLibraries_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("YAC")
JLLWrappers.@declare_library_product(libyac_core, "@rpath/libyac_core.dylib")
JLLWrappers.@declare_library_product(libyac_mci, "@rpath/libyac_mci.dylib")
JLLWrappers.@declare_library_product(libyac_mtime, "@rpath/libyac_mtime.dylib")
JLLWrappers.@declare_library_product(libyac_pak, "@rpath/libyac_pak.dylib")
JLLWrappers.@declare_library_product(libyac_utils, "@rpath/libyac_utils.dylib")
function __init__()
    JLLWrappers.@generate_init_header(yaxt_jll, libfyaml_jll, NetCDF_jll, OpenBLAS32_jll, CompilerSupportLibraries_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libyac_core,
        "lib/libyac_core.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_mci,
        "lib/libyac_mci.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_mtime,
        "lib/libyac_mtime.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_pak,
        "lib/libyac_pak.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyac_utils,
        "lib/libyac_utils.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
